(** {1 Elliptic curve cryptography} *)

(** Mirage-crypto-ec implements public key cryptography with named elliptic
    curves. Ephemeral key exchanges with {{!Dh}Diffie-Hellman} and
    {{!Dsa}digital signatures (ECDSA)} are implemented.

    The arithmetic operations uses code generated by
    {{:https://github.com/mit-plv/fiat-crypto}fiat-crypto} which is proven to
    consume a constant amount of time, independent of the input values.
*)

type error = [
  | `Invalid_range
  | `Invalid_format
  | `Invalid_length
  | `Not_on_curve
  | `At_infinity
  | `Low_order
]
(** The type for errors. *)

val pp_error : Format.formatter -> error -> unit
(** Pretty printer for errors *)

exception Message_too_long
(** Raised if the provided message is too long for the curve. *)

(** Diffie-Hellman key exchange. *)
module type Dh = sig

  type secret
  (** Type for private keys. *)

  val secret_of_octets : ?compress:bool -> string ->
    (secret * string, error) result
  (** [secret_of_octets ~compress secret] decodes the provided buffer as
      {!secret}.  If [compress] is provided and [true] (defaults to [false]),
      the shared part will be compressed. May result in an error if the buffer
      had an invalid length or was not in bounds. *)

  val secret_to_octets : secret -> string
  (** [secret_to_octets secret] encodes the provided secret into a freshly
      allocated buffer. *)

  val gen_key : ?compress:bool -> ?g:Mirage_crypto_rng.g -> unit ->
    secret * string
  (** [gen_key ~compress ~g ()] generates a private and a public key for
      Ephemeral Diffie-Hellman. If [compress] is provided and [true] (defaults
      to [false]), the shared part will be compressed. The returned key pair
      MUST only be used for a single key exchange.

      The generated private key is checked to be greater than zero and lower
      than the group order meaning the public key cannot be the point at
      inifinity. *)

  val key_exchange : secret -> string -> (string, error) result
  (** [key_exchange secret received_public_key] performs Diffie-Hellman key
      exchange using your secret and the data received from the other party.
      Returns the shared secret or an error if the received data is wrongly
      encoded, doesn't represent a point on the curve or represent the point
      at infinity.

      The shared secret is returned as is i.e. not stripped from leading 0x00
      bytes.

      The public key encoding is described
      {{:http://www.secg.org/sec1-v2.pdf}in SEC 1} from SECG. *)
end

(** Digital signature algorithm. *)
module type Dsa = sig

  type priv
  (** The type for private keys. *)

  type pub
  (** The type for public keys. *)

  val byte_length : int
  (** [byte_length] is the size of a ECDSA signature in bytes. *)

  val bit_length : int
  (** [bit_length] is the number of significant bits in a ECDSA signature *)

  (** {2 Serialisation} *)

  val priv_of_octets : string -> (priv, error) result
  (** [priv_of_octets buf] decodes a private key from the buffer [buf]. If the
      provided data is invalid, an error is returned. *)

  val priv_to_octets : priv -> string
  (** [priv_to_octets p] encode the private key [p] to a buffer. *)

  val pub_of_octets : string -> (pub, error) result
  (** [pub_of_octets buf] decodes a public key from the buffer [buf]. If the
      provided data is invalid, an error is returned. *)

  val pub_to_octets : ?compress:bool -> pub -> string
  (** [pub_to_octets ~compress p] encodes the public key [p] into a buffer.
      If [compress] is provided and [true] (default [false]), the compressed
      representation is returned. *)

  (** {2 Deriving the public key} *)

  val pub_of_priv : priv -> pub
  (** [pub_of_priv p] extracts the public key from the private key [p]. *)

  (** {2 Key generation} *)

  val generate : ?g:Mirage_crypto_rng.g -> unit -> priv * pub
  (** [generate ~g ()] generates a key pair. *)

  (** {2 Cryptographic operations} *)

  val sign : key:priv -> ?k:string -> string -> string * string
  (** [sign ~key ~k digest] signs the message [digest] using the private
      [key]. The [digest] is not processed further - it should be the hash of
      the message to sign. If [k] is not provided, it is computed using the
      deterministic construction from RFC 6979. The result is a pair of [r]
      and [s].

      Warning: there {{:https://www.hertzbleed.com/2h2b.pdf}are}
      {{:https://www.hertzbleed.com/hertzbleed.pdf}attacks} that recover the
      private key from a power and timing analysis of the RFC 6979 computation
      of [k] - thus it is advised to provide a good nonce ([k]) explicitly,
      which is independent of key and digest.

      @raise Invalid_argument if [k] is not suitable or not in range.
      @raise Message_too_long if the bit size of [msg] exceeds the curve. *)

  val verify : key:pub -> string * string -> string -> bool
  (** [verify ~key (r, s) digest] verifies the signature [r, s] on the message
      [digest] with the public [key]. The return value is [true] if verification
      was successful, [false] otherwise. If the message has more bits than the
      group order, the result is false. *)

  (** [K_gen] can be instantiated over a hashing module to obtain an RFC6979
      compliant [k]-generator for that hash. *)
  module K_gen (H : Digestif.S) : sig

    val generate : key:priv -> string -> string
    (** [generate ~key digest] deterministically takes the given private key
        and message digest to a [k] suitable for seeding the signing process. *)
  end

end

(** BIP-340 Schnorr signature algorithm on curve secp256k1. *)
module type Dsa_bip340 = sig
  include Dsa

  (** {2 Serialisation} *)

  val get_x : pub -> string
  (** [get_x p] returns the X coordinate of public key [p]. *)

  (** {2 Cryptographic operations} *)

  val sign_bip340 : key:priv -> ?aux_rand:string -> string -> string * string
  (** [sign ~key ~aux_rand msg] signs the message [msg] using the private [key].
      If [aux_rand] is provided, it is used as auxiliary randomness in the
      deterministic nonce generation process. Otherwise, fresh randomness is
      generated.

      The BIP-340 signing algorithm implements key prefixing to prevent key
      recovery in multi-user settings. The result is a pair of [r] and [s] where
      [r] is the X coordinate of the nonce point R, and [s] is the signature
      scalar.

      Note that unlike ECDSA, BIP-340 signatures do not require pre-hashing of
      the message, though pre-hashing is recommended for large messages.

      @raise Invalid_argument if the signature cannot be generated. *)

  val verify_bip340 : key:pub -> string * string -> string -> bool
  (** [verify ~x (r, s) msg] verifies the BIP-340 Schnorr signature [r, s]
      on the message [msg] with the public [x] coordinate. The return value is
      [true] if verification was successful, [false] otherwise.

      The verification checks that s⋅G = R + hash(R || P || m)⋅P, where
      R is the point with x-coordinate r and even y-coordinate,
      P is the point with x-coordinate from the public key and even y-coordinate,
      and m is the message. *)

end

(** Elliptic curve with Diffie-Hellman and DSA. *)
module type Dh_dsa = sig

  (** Diffie-Hellman key exchange. *)
  module Dh : Dh

  (** Digital signature algorithm. *)
  module Dsa : Dsa
end

(** secp256k1 with Diffie-Hellman, DSA and BIP-340. *)
module type P256k1 = sig
  include Dh_dsa

  (** Digital signature algorithm. *)
  module Dsa_bip340 : Dsa_bip340 with type priv = Dsa.priv and type pub = Dsa.pub

end


(** The NIST P-256 curve, also known as SECP256R1. *)
module P256 : Dh_dsa

(** The NIST P-384 curve, also known as SECP384R1. *)
module P384 : Dh_dsa

(** The NIST P-521 curve, also known as SECP521R1. *)
module P521 : Dh_dsa

(** The SECP256K1 curve. *)
module P256k1 : P256k1

(** The BrainpoolP256r1 curve. *)
module BrainpoolP256 : Dh_dsa

(** The BrainpoolP384r1 curve. *)
module BrainpoolP384 : Dh_dsa

(** The BrainpoolP512r1 curve. *)
module BrainpoolP512 : Dh_dsa

(** Curve 25519 Diffie-Hellman, also known as X25519. *)
module X25519 : Dh

(** Curve 25519 DSA, also known as Ed25519. *)
module Ed25519 : sig
  type priv
  (** The type for private keys. *)

  type pub
  (** The type for public keys. *)

  (** {2 Serialisation} *)

  val priv_of_octets : string -> (priv, error) result
  (** [priv_of_octets buf] decodes a private key from the buffer [buf]. If the
      provided data is invalid, an error is returned. *)

  val priv_to_octets : priv -> string
  (** [priv_to_octets p] encode the private key [p] to a buffer. *)

  val pub_of_octets : string -> (pub, error) result
  (** [pub_of_octets buf] decodes a public key from the buffer [buf]. If the
      provided data is invalid, an error is returned. *)

  val pub_to_octets : pub -> string
  (** [pub_to_octets p] encodes the public key [p] into a buffer. *)

  (** {2 Deriving the public key} *)

  val pub_of_priv : priv -> pub
  (** [pub_of_priv p] extracts the public key from the private key [p]. *)

  (** {2 Key generation} *)

  val generate : ?g:Mirage_crypto_rng.g -> unit -> priv * pub
  (** [generate ~g ()] generates a key pair. *)

  (** {2 Cryptographic operations} *)

  val sign : key:priv -> string -> string
  (** [sign ~key msg] signs the message [msg] using the private [key]. The
      result is the concatenation of [r] and [s], as specified in RFC 8032. *)

  val verify : key:pub -> string -> msg:string -> bool
  (** [verify ~key signature msg] verifies the [signature] on the message
      [msg] with the public [key]. The return value is [true] if verification
      was successful, [false] otherwise. *)

  (** {2 Low-level primitives}

      Direct access to the underlying scalar and group arithmetic, for
      building higher-level constructions (such as BIP32-Ed25519
      hierarchical key derivation) that need more than opaque
      sign/verify. Scalars are 32-byte little-endian values interpreted
      modulo the group order [L]; points are 32-byte RFC 8032 encodings.
      Point decoding is variable-time: {b not} constant time. *)
  module Primitive : sig
    val scalar_reduce : string -> string
    (** [scalar_reduce wide] reduces the 64-byte little-endian value
        [wide] modulo [L], returning a 32-byte scalar.
        @raise Invalid_argument if [wide] is not 64 bytes. *)

    val scalar_muladd : string -> string -> string -> string
    (** [scalar_muladd a b c] is [(a * b + c) mod L] over 32-byte
        little-endian scalars. *)

    val scalar_mult_base : string -> string
    (** [scalar_mult_base s] is the RFC 8032 encoding of [s * B] for the
        Ed25519 base point [B] and 32-byte scalar [s]. *)

    val point_add : string -> string -> (string, error) result
    (** [point_add p q] adds two RFC 8032-encoded points, returning the
        encoding of [p + q], or [Error `Not_on_curve] if either point
        fails to decode. *)

    val point_valid : string -> bool
    (** [point_valid p] is [true] iff [p] is a valid 32-byte RFC 8032
        point encoding. *)

    val verify_double_base : k:string -> pub:string -> s:string -> bool * string
    (** [verify_double_base ~k ~pub ~s] returns [(ok, r)] where [r] is the
        RFC 8032 encoding of [s * B - k * P] (with [P] the point encoded
        by [pub]) and [ok] is [false] if [pub] fails to decode. This is
        the core relation checked by Ed25519 {!verify}. *)
  end
end
