(** {1 Elliptic curve cryptography} *)

(** Mirage-crypto-ec implements public key cryptography with named elliptic
    curves. Ephemeral key exchanges with {{!Dh}Diffie-Hellman} and
    {{!Dsa}digital signatures (ECDSA)} are implemented.

    The arithmetic operations uses code generated by
    {{:https://github.com/mit-plv/fiat-crypto}fiat-crypto} which is proven to
    consume a constant amount of time, independent of the input values.
*)

type error = [
  | `Invalid_range
  | `Invalid_format
  | `Invalid_length
  | `Not_on_curve
  | `At_infinity
  | `Low_order
]
(** The type for errors. *)

val pp_error : Format.formatter -> error -> unit
(** Pretty printer for errors *)

exception Message_too_long
(** Raised if the provided message is too long for the curve. *)

(** Diffie-Hellman key exchange. *)
module type Dh = sig

  type secret
  (** Type for private keys. *)

  val secret_of_octets : ?compress:bool -> string ->
    (secret * string, error) result
  (** [secret_of_octets ~compress secret] decodes the provided buffer as
      {!secret}.  If [compress] is provided and [true] (defaults to [false]),
      the shared part will be compressed. May result in an error if the buffer
      had an invalid length or was not in bounds. *)

  val secret_to_octets : secret -> string
  (** [secret_to_octets secret] encodes the provided secret into a freshly
      allocated buffer. *)

  val gen_key : ?compress:bool -> ?g:Mirage_crypto_rng.g -> unit ->
    secret * string
  (** [gen_key ~compress ~g ()] generates a private and a public key for
      Ephemeral Diffie-Hellman. If [compress] is provided and [true] (defaults
      to [false]), the shared part will be compressed. The returned key pair
      MUST only be used for a single key exchange.

      The generated private key is checked to be greater than zero and lower
      than the group order meaning the public key cannot be the point at
      inifinity. *)

  val key_exchange : secret -> string -> (string, error) result
  (** [key_exchange secret received_public_key] performs Diffie-Hellman key
      exchange using your secret and the data received from the other party.
      Returns the shared secret or an error if the received data is wrongly
      encoded, doesn't represent a point on the curve or represent the point
      at infinity.

      The shared secret is returned as is i.e. not stripped from leading 0x00
      bytes.

      The public key encoding is described
      {{:http://www.secg.org/sec1-v2.pdf}in SEC 1} from SECG. *)
end

(** Digital signature algorithm. *)
module type Dsa = sig

  type priv
  (** The type for private keys. *)

  type pub
  (** The type for public keys. *)

  val byte_length : int
  (** [byte_length] is the size of a ECDSA signature in bytes. *)

  val bit_length : int
  (** [bit_length] is the number of significant bits in a ECDSA signature *)

  (** {2 Serialisation} *)

  val priv_of_octets : string -> (priv, error) result
  (** [priv_of_octets buf] decodes a private key from the buffer [buf]. If the
      provided data is invalid, an error is returned. *)

  val priv_to_octets : priv -> string
  (** [priv_to_octets p] encode the private key [p] to a buffer. *)

  val pub_of_octets : string -> (pub, error) result
  (** [pub_of_octets buf] decodes a public key from the buffer [buf]. If the
      provided data is invalid, an error is returned. *)

  val pub_to_octets : ?compress:bool -> pub -> string
  (** [pub_to_octets ~compress p] encodes the public key [p] into a buffer.
      If [compress] is provided and [true] (default [false]), the compressed
      representation is returned. *)

  (** {2 Deriving the public key} *)

  val pub_of_priv : priv -> pub
  (** [pub_of_priv p] extracts the public key from the private key [p]. *)

  val add_scalar : priv -> priv -> (priv, error) result
  (** [add_scalar a b] is the private key [(a + b) mod n], where [n] is the
      group order, or [Error `Invalid_range] if the sum is zero.

      Constant time. This is the scalar half of the additive key derivation
      that BIP32 hierarchical wallets and BIP341 Taproot output keys are
      built from; without it a caller has to leave the library to do
      arbitrary-precision arithmetic on a secret, which is exactly where a
      timing leak gets reintroduced. *)

  (** {2 Key generation} *)

  val generate : ?g:Mirage_crypto_rng.g -> unit -> priv * pub
  (** [generate ~g ()] generates a key pair. *)

  (** {2 Cryptographic operations} *)

  val sign : key:priv -> ?k:string -> string -> string * string
  (** [sign ~key ~k digest] signs the message [digest] using the private
      [key]. The [digest] is not processed further - it should be the hash of
      the message to sign. If [k] is not provided, it is computed using the
      deterministic construction from RFC 6979. The result is a pair of [r]
      and [s].

      Warning: there {{:https://www.hertzbleed.com/2h2b.pdf}are}
      {{:https://www.hertzbleed.com/hertzbleed.pdf}attacks} that recover the
      private key from a power and timing analysis of the RFC 6979 computation
      of [k] - thus it is advised to provide a good nonce ([k]) explicitly,
      which is independent of key and digest.

      @raise Invalid_argument if [k] is not suitable or not in range.
      @raise Message_too_long if the bit size of [msg] exceeds the curve. *)

  val verify : key:pub -> string * string -> string -> bool
  (** [verify ~key (r, s) digest] verifies the signature [r, s] on the message
      [digest] with the public [key]. The return value is [true] if verification
      was successful, [false] otherwise. If the message has more bits than the
      group order, the result is false. *)

  (** [K_gen] can be instantiated over a hashing module to obtain an RFC6979
      compliant [k]-generator for that hash. *)
  module K_gen (H : Digestif.S) : sig

    val generate : key:priv -> string -> string
    (** [generate ~key digest] deterministically takes the given private key
        and message digest to a [k] suitable for seeding the signing process. *)
  end

end

(** BIP-340 Schnorr signature algorithm on curve secp256k1. *)
module type Dsa_bip340 = sig
  include Dsa

  val negate_scalar : priv -> priv
  (** [negate_scalar d] is the private key [n - d], where [n] is the group
      order. Constant time.

      BIP340 defines signing against the point with even [y], and BIP341
      tweaks against [lift_x] of the internal key, so both need this when the
      key's point has odd [y]. {!sign_bip340} applies it internally; callers
      preparing a Taproot output key need it themselves. *)

  (** {2 Serialisation} *)

  val get_x : pub -> string
  (** [get_x p] returns the X coordinate of public key [p]. *)

  (** {2 Cryptographic operations} *)

  val sign_bip340 : key:priv -> ?aux_rand:string -> string -> string * string
  (** [sign ~key ~aux_rand msg] signs the message [msg] using the private [key].
      If [aux_rand] is provided, it is used as auxiliary randomness in the
      deterministic nonce generation process. Otherwise, fresh randomness is
      generated.

      The BIP-340 signing algorithm implements key prefixing to prevent key
      recovery in multi-user settings. The result is a pair of [r] and [s] where
      [r] is the X coordinate of the nonce point R, and [s] is the signature
      scalar.

      Note that unlike ECDSA, BIP-340 signatures do not require pre-hashing of
      the message, though pre-hashing is recommended for large messages.

      @raise Invalid_argument if the signature cannot be generated. *)

  val verify_bip340 : key:pub -> string * string -> string -> bool
  (** [verify ~x (r, s) msg] verifies the BIP-340 Schnorr signature [r, s]
      on the message [msg] with the public [x] coordinate. The return value is
      [true] if verification was successful, [false] otherwise.

      The verification checks that s⋅G = R + hash(R || P || m)⋅P, where
      R is the point with x-coordinate r and even y-coordinate,
      P is the point with x-coordinate from the public key and even y-coordinate,
      and m is the message. *)

end

(** Elliptic curve with Diffie-Hellman and DSA. *)
module type Dh_dsa = sig

  (** Diffie-Hellman key exchange. *)
  module Dh : Dh

  (** Digital signature algorithm. *)
  module Dsa : Dsa
end

(** secp256k1 with Diffie-Hellman, DSA and BIP-340. *)
module type P256k1 = sig
  include Dh_dsa

  (** Digital signature algorithm. *)
  module Dsa_bip340 : Dsa_bip340 with type priv = Dsa.priv and type pub = Dsa.pub

  (** {2 Low-level primitives}

      Direct access to the underlying scalar and group arithmetic, for
      building higher-level constructions (such as FROST threshold
      signatures) that need more than opaque sign/verify. Scalars are
      32-byte big-endian values in the scalar field mod [n], the group
      order; on the wire, points use the
      {{:http://www.secg.org/sec1-v2.pdf}SEC 1} encoding.

      The scalar arithmetic is fiat-crypto generated word-by-word
      Montgomery code and runs in constant time; each operation's inputs
      are reduced modulo [n] when loaded (the same property the ECDSA
      code relies on for message digests), and its output is the
      canonical representative in [[0, n)]. Use {!scalar_of_octets} when
      a value is required to already be canonical. Point encoding and
      decoding operate on public values and are {b not} constant
      time. *)
  module Primitive : sig

    type point
    (** The type for points on the curve, including the point at
        infinity (the group identity). *)

    (** {2 Scalars mod n} *)

    val scalar_zero : string
    (** [scalar_zero] is the scalar 0. *)

    val scalar_one : string
    (** [scalar_one] is the scalar 1. *)

    val scalar_of_octets : string -> (string, error) result
    (** [scalar_of_octets buf] validates [buf] as a canonical scalar:
        32 bytes, big-endian, in the range [[0, n)]. Returns the scalar
        unchanged (scalars are their own encoding), [Error
        `Invalid_length] or [Error `Invalid_range] otherwise. Unlike
        {!Dsa.priv_of_octets}, zero is accepted: it is a valid scalar
        field element, just not a valid private key. The comparison is
        constant time. *)

    val scalar_add : string -> string -> string
    (** [scalar_add a b] is [(a + b) mod n]. Constant time. *)

    val scalar_add_into : bytes -> string -> string -> unit
    (** [scalar_add_into dst a b] writes [(a + b) mod n] into the
        32-byte [dst]. Same computation as {!scalar_add}, but the caller
        supplies the destination, so a secret scalar can be kept in a
        buffer the caller is able to overwrite once it is no longer
        needed; internal temporaries are wiped before returning.
        @raise Invalid_argument if [dst], [a], or [b] is not 32 bytes. *)

    val scalar_mul : string -> string -> string
    (** [scalar_mul a b] is [(a * b) mod n]. Constant time. *)

    val scalar_mul_into : bytes -> string -> string -> unit
    (** [scalar_mul_into dst a b] writes [(a * b) mod n] into the
        32-byte [dst]. Same computation as {!scalar_mul}, with a
        caller-supplied destination and wiped temporaries, as
        {!scalar_add_into}.
        @raise Invalid_argument if [dst], [a], or [b] is not 32 bytes. *)

    val scalar_negate : string -> string
    (** [scalar_negate a] is [(n - a) mod n]; the negation of zero is
        zero. Constant time. *)

    val scalar_negate_into : bytes -> string -> unit
    (** [scalar_negate_into dst a] writes [(n - a) mod n] into the
        32-byte [dst]. Same computation as {!scalar_negate}, with a
        caller-supplied destination and wiped temporaries, as
        {!scalar_add_into}.
        @raise Invalid_argument if [dst] or [a] is not 32 bytes. *)

    val scalar_inv : string -> string
    (** [scalar_inv a] is the multiplicative inverse [a^(-1) mod n],
        computed by Bernstein-Yang inversion with a fixed iteration
        count: constant time. By convention [scalar_inv scalar_zero] is
        [scalar_zero] (zero has no inverse). *)

    val scalar_inv_into : bytes -> string -> unit
    (** [scalar_inv_into dst a] writes [a^(-1) mod n] into the 32-byte
        [dst]. Same computation as {!scalar_inv}, with a caller-supplied
        destination and wiped temporaries, as {!scalar_add_into}.
        @raise Invalid_argument if [dst] or [a] is not 32 bytes. *)

    (** {2 Points} *)

    val point_of_octets : string -> (point, error) result
    (** [point_of_octets buf] decodes a SEC 1 encoded point: compressed
        (33 bytes, [0x02]/[0x03] prefix) or uncompressed (65 bytes,
        [0x04] prefix). The coordinates are validated to be in range and
        on the curve; the encoding of the point at infinity (a single
        [0x00] byte) is rejected with [Error `At_infinity].

        This operates on a public value, so it is not constant time. *)

    val point_to_octets : point -> string
    (** [point_to_octets p] is the compressed SEC 1 encoding of [p]
        (33 bytes). The point at infinity — which {!point_of_octets}
        does not accept back, but {!point_add} can produce — encodes as
        a single [0x00] byte.

        This is intended for public values, and is not constant time. *)

    val point_add : point -> point -> point
    (** [point_add p q] is the group law: [p + q]. Computed with a
        complete (unified) projective addition formula, so it is correct
        for all inputs — [p = q] (doubling), the identity on either
        side, and inverse points, in which case the result is the
        identity. The formula is branch-free and identity inputs and
        outputs are handled with constant-time selects. *)

    val point_is_infinity : point -> bool
    (** [point_is_infinity p] is [true] iff [p] is the point at infinity
        (the group identity). *)

    val scalar_mult : string -> point -> point
    (** [scalar_mult k p] is [k * p], the scalar multiple of [p] by the
        32-byte big-endian scalar [k], for [k] in [[1, n - 1]].
        [scalar_mult k p] is [p] when [p] is the identity.

        The multiplication is a regular-wNAF ladder with a fixed
        sequence of complete point operations and constant-time table
        lookups: constant time with respect to [k] (and to the
        coordinates of [p]), which is what allows applying it to secret
        key shares. Whether [p] is the identity is decided by a branch,
        so only that fact — never [k] — is timing-visible.
        @raise Invalid_argument if [k] is not 32 bytes or not in
        [[1, n - 1]]. *)

    val scalar_mult_base : string -> point
    (** [scalar_mult_base k] is [k * G] for the secp256k1 base point
        [G] and [k] in [[1, n - 1]]. Fixed-base comb multiplication with
        constant-time table lookups: constant time with respect to [k].
        @raise Invalid_argument if [k] is not 32 bytes or not in
        [[1, n - 1]]. *)
  end
end


(** The NIST P-256 curve, also known as SECP256R1. *)
module P256 : Dh_dsa

(** The NIST P-384 curve, also known as SECP384R1. *)
module P384 : Dh_dsa

(** The NIST P-521 curve, also known as SECP521R1. *)
module P521 : Dh_dsa

(** The SECP256K1 curve. *)
module P256k1 : P256k1

(** The BrainpoolP256r1 curve. *)
module BrainpoolP256 : Dh_dsa

(** The BrainpoolP384r1 curve. *)
module BrainpoolP384 : Dh_dsa

(** The BrainpoolP512r1 curve. *)
module BrainpoolP512 : Dh_dsa

(** Curve 25519 Diffie-Hellman, also known as X25519. *)
module X25519 : Dh

(** Curve 25519 DSA, also known as Ed25519. *)
module Ed25519 : sig
  type priv
  (** The type for private keys. *)

  type pub
  (** The type for public keys. *)

  (** {2 Serialisation} *)

  val priv_of_octets : string -> (priv, error) result
  (** [priv_of_octets buf] decodes a private key from the buffer [buf]. If the
      provided data is invalid, an error is returned. *)

  val priv_to_octets : priv -> string
  (** [priv_to_octets p] encode the private key [p] to a buffer. *)

  val pub_of_octets : string -> (pub, error) result
  (** [pub_of_octets buf] decodes a public key from the buffer [buf]. If the
      provided data is invalid, an error is returned. *)

  val pub_to_octets : pub -> string
  (** [pub_to_octets p] encodes the public key [p] into a buffer. *)

  (** {2 Deriving the public key} *)

  val pub_of_priv : priv -> pub
  (** [pub_of_priv p] extracts the public key from the private key [p]. *)

  (** {2 Key generation} *)

  val generate : ?g:Mirage_crypto_rng.g -> unit -> priv * pub
  (** [generate ~g ()] generates a key pair. *)

  (** {2 Cryptographic operations} *)

  val sign : key:priv -> string -> string
  (** [sign ~key msg] signs the message [msg] using the private [key]. The
      result is the concatenation of [r] and [s], as specified in RFC 8032. *)

  val verify : key:pub -> string -> msg:string -> bool
  (** [verify ~key signature msg] verifies the [signature] on the message
      [msg] with the public [key]. The return value is [true] if verification
      was successful, [false] otherwise. *)

  (** {2 Low-level primitives}

      Direct access to the underlying scalar and group arithmetic, for
      building higher-level constructions (such as BIP32-Ed25519
      hierarchical key derivation) that need more than opaque
      sign/verify. Scalars are 32-byte little-endian values interpreted
      modulo the group order [L]; points are 32-byte RFC 8032 encodings.
      Point decoding is variable-time: {b not} constant time. *)
  module Primitive : sig
    val to_x25519_pub : string -> (string, error) result
    (** [to_x25519_pub pub] maps an Ed25519 public key to the corresponding
        Curve25519 u-coordinate, via the birational map
        [u = (1 + y) / (1 - y)]. This is what protocols that sign with
        Ed25519 and key-exchange with X25519 need in order to derive a shared
        secret from a peer's signing key.

        Only [y] is used, so the sign bit is ignored and no point
        decompression takes place. Returns [Error `Not_on_curve] for [y = 1],
        the one input with no Montgomery image.

        This operates on a public value, so it is not constant time.
        @raise Invalid_argument if [pub] is not 32 bytes. *)

    val to_x25519_priv : string -> string
    (** [to_x25519_priv secret] is the X25519 scalar for an Ed25519 private
        key: the clamped low half of [SHA-512 secret], as RFC 8032 derives for
        signing.
        @raise Invalid_argument if [secret] is not 32 bytes. *)

    val scalar_reduce : string -> string
    (** [scalar_reduce wide] reduces the 64-byte little-endian value
        [wide] modulo [L], returning a 32-byte scalar.
        @raise Invalid_argument if [wide] is not 64 bytes. *)

    val scalar_reduce_into : bytes -> string -> unit
    (** [scalar_reduce_into dst wide] reduces the 64-byte little-endian
        value [wide] modulo [L], writing the 32-byte scalar into [dst].
        Same computation as {!scalar_reduce}, but the caller supplies the
        destination, so a secret scalar can be kept in a buffer the
        caller is able to overwrite once it is no longer needed.
        @raise Invalid_argument if [dst] is not 32 bytes or [wide] is not
        64 bytes. *)

    val scalar_muladd : string -> string -> string -> string
    (** [scalar_muladd a b c] is [(a * b + c) mod L] over 32-byte
        little-endian scalars. *)

    val scalar_muladd_into : bytes -> string -> string -> string -> unit
    (** [scalar_muladd_into dst a b c] writes [(a * b + c) mod L] over
        32-byte little-endian scalars into the 32-byte [dst]. Same
        computation as {!scalar_muladd}, but the caller supplies the
        destination, so a secret scalar can be kept in a buffer the
        caller is able to overwrite once it is no longer needed.
        @raise Invalid_argument if [dst], [a], [b], or [c] is not 32
        bytes. *)

    val scalar_mult_base : string -> string
    (** [scalar_mult_base s] is the RFC 8032 encoding of [s * B] for the
        Ed25519 base point [B] and 32-byte scalar [s]. *)

    val scalar_mult_base_into : bytes -> string -> unit
    (** [scalar_mult_base_into dst s] writes the RFC 8032 encoding of
        [s * B], for the Ed25519 base point [B] and 32-byte scalar [s],
        into the 32-byte [dst]. Same computation as {!scalar_mult_base},
        with a caller-supplied destination.
        @raise Invalid_argument if [dst] or [s] is not 32 bytes. *)

    val point_add : string -> string -> (string, error) result
    (** [point_add p q] adds two RFC 8032-encoded points, returning the
        encoding of [p + q], or [Error `Not_on_curve] if either point
        fails to decode. *)

    val point_valid : string -> bool
    (** [point_valid p] is [true] iff [p] is a valid 32-byte RFC 8032
        point encoding. *)

    val verify_double_base : k:string -> pub:string -> s:string -> bool * string
    (** [verify_double_base ~k ~pub ~s] returns [(ok, r)] where [r] is the
        RFC 8032 encoding of [s * B - k * P] (with [P] the point encoded
        by [pub]) and [ok] is [false] if [pub] fails to decode. This is
        the core relation checked by Ed25519 {!verify}. *)
  end
end
