(test (name smoke) (modules smoke) (package mirage-crypto-ed25519-bip32)
 (modes byte exe) (libraries mirage-crypto-ed25519-bip32))
(test (name vectors) (modules vectors) (package mirage-crypto-ed25519-bip32)
 (deps rust-vectors.tsv icarus-vectors.tsv cardano-vectors.tsv master-vectors.tsv)
 (modes byte exe) (libraries mirage-crypto-ed25519-bip32))
(test (name edges) (modules edges) (package mirage-crypto-ed25519-bip32)
 (modes byte exe) (libraries mirage-crypto-ed25519-bip32))
(test (name domains) (modules domains) (package mirage-crypto-ed25519-bip32)
 (enabled_if (>= %{ocaml_version} 5.0))
 (libraries mirage-crypto-ed25519-bip32))
