/* Generated by tools/select-portable-crypto.py. Do not edit.
 * Selected helpers below retain the upstream MIT license in vendor/LICENSE.txt.
 */
#ifndef MC_PORTABLE_INNER_H
#define MC_PORTABLE_INNER_H
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#define BR_LE_UNALIGNED 0
#define BR_BE_UNALIGNED 0
#define br_aes_ct_bitslice_Sbox mc_bear_aes_ct_bitslice_Sbox
#define br_aes_ct_bitslice_invSbox mc_bear_aes_ct_bitslice_invSbox
#define br_aes_ct_ortho mc_bear_aes_ct_ortho
#define br_aes_ct_keysched mc_bear_aes_ct_keysched
#define br_aes_ct_skey_expand mc_bear_aes_ct_skey_expand
#define br_aes_ct_bitslice_encrypt mc_bear_aes_ct_bitslice_encrypt
#define br_aes_ct_bitslice_decrypt mc_bear_aes_ct_bitslice_decrypt
#define br_ghash_ctmul32 mc_bear_ghash_ctmul32
static inline void
br_enc32le(void *dst, uint32_t x)
{
#if BR_LE_UNALIGNED
	((br_union_u32 *)dst)->u = x;
#else
	unsigned char *buf;

	buf = dst;
	buf[0] = (unsigned char)x;
	buf[1] = (unsigned char)(x >> 8);
	buf[2] = (unsigned char)(x >> 16);
	buf[3] = (unsigned char)(x >> 24);
#endif
}

static inline void
br_enc32be(void *dst, uint32_t x)
{
#if BR_BE_UNALIGNED
	((br_union_u32 *)dst)->u = x;
#else
	unsigned char *buf;

	buf = dst;
	buf[0] = (unsigned char)(x >> 24);
	buf[1] = (unsigned char)(x >> 16);
	buf[2] = (unsigned char)(x >> 8);
	buf[3] = (unsigned char)x;
#endif
}

static inline uint32_t
br_dec32le(const void *src)
{
#if BR_LE_UNALIGNED
	return ((const br_union_u32 *)src)->u;
#else
	const unsigned char *buf;

	buf = src;
	return (uint32_t)buf[0]
		| ((uint32_t)buf[1] << 8)
		| ((uint32_t)buf[2] << 16)
		| ((uint32_t)buf[3] << 24);
#endif
}

static inline uint32_t
br_dec32be(const void *src)
{
#if BR_BE_UNALIGNED
	return ((const br_union_u32 *)src)->u;
#else
	const unsigned char *buf;

	buf = src;
	return ((uint32_t)buf[0] << 24)
		| ((uint32_t)buf[1] << 16)
		| ((uint32_t)buf[2] << 8)
		| (uint32_t)buf[3];
#endif
}


void br_aes_ct_bitslice_Sbox(uint32_t *q);
void br_aes_ct_bitslice_invSbox(uint32_t *q);
void br_aes_ct_ortho(uint32_t *q);
unsigned br_aes_ct_keysched(uint32_t *comp_skey, const void *key, size_t key_len);
void br_aes_ct_skey_expand(uint32_t *skey, unsigned rounds, const uint32_t *comp);
void br_aes_ct_bitslice_encrypt(unsigned rounds, const uint32_t *skey, uint32_t *q);
void br_aes_ct_bitslice_decrypt(unsigned rounds, const uint32_t *skey, uint32_t *q);
void br_ghash_ctmul32(void *y, const void *h, const void *data, size_t len);
#endif
