(library
 (name mirage_crypto_secp256k1)
 (public_name mirage-crypto-secp256k1)
 (libraries mirage-crypto-rng)
 (foreign_stubs
  (language c)
  (names k1_kernel k1_precomputed k1_precomputed_gen k1_stubs)
  (extra_deps (source_tree vendor))
  (flags (:standard -O2 -std=c99 -DENABLE_MODULE_RECOVERY
    -DENABLE_MODULE_EXTRAKEYS -DENABLE_MODULE_SCHNORRSIG
    -DECMULT_WINDOW_SIZE=8 -DCOMB_BLOCKS=2 -DCOMB_TEETH=5))))

(install (package mirage-crypto-secp256k1) (section doc)
 (files ../BACKENDS.md vendor/manifest.json vendor/COPYING))
