(library
 (name mirage_crypto_blockchain)
 (public_name mirage-crypto-blockchain)
 (libraries
  mirage-crypto-blockchain-core
  zarith mirage-crypto mirage-crypto-rng mirage-crypto-ec digestif eqaf)
 (private_modules
  octets hashes
  ripemd160 keccak keccak256 blake3
  secp256k1 bip340 stark_curve poseidon
  bls12_381 sr25519))
