(library
 (name mirage_crypto_blockchain)
 (public_name mirage-crypto-blockchain)
 (libraries
  mirage-crypto-bip32 mirage-crypto-sr25519 mirage-crypto-blockchain-core mirage-crypto-poseidon mirage-crypto-bls12-381 mirage-crypto-blake3 mirage-crypto-secp256k1
  zarith mirage-crypto mirage-crypto-rng mirage-crypto-ec digestif eqaf)
 (private_modules
  octets hashes
  ripemd160 keccak keccak256 blake3
  secp256k1 bip340 stark_curve poseidon
  bls12_381 sr25519))

(install (package mirage-crypto-blockchain) (section doc)
 (files ../BACKENDS.md))
