#!/usr/bin/env python3
"""Verify BearSSL imports and reproduce the minimal private header."""
import argparse
import hashlib
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent / 'src/native/portable'
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
base = root / 'vendor'
manifest = json.loads((base / 'manifest.json').read_text())
expected = set(manifest['sha256']) | {'manifest.json', 'dune'}
actual = {str(p.relative_to(base)) for p in base.rglob('*') if p.is_file()}
if actual != expected:
    raise SystemExit(f'BearSSL inventory mismatch: {actual ^ expected}')
for name, digest in manifest['sha256'].items():
    if hashlib.sha256((base / name).read_bytes()).hexdigest() != digest:
        raise SystemExit(f'BearSSL source mismatch: {name}')

inner = (base / 'src/inner.h').read_text()
# Exact upstream byte-order helpers, with portable unaligned-safe paths selected.
start = inner.index('static inline void\nbr_enc32le(')
end = inner.index('static inline void\nbr_enc64le(', start)
symbols = ['bitslice_Sbox', 'bitslice_invSbox', 'ortho', 'keysched',
           'skey_expand', 'bitslice_encrypt', 'bitslice_decrypt']
header = '''/* Generated by tools/select-portable-crypto.py. Do not edit.
 * Selected helpers below retain the upstream MIT license in vendor/LICENSE.txt.
 */
#ifndef MC_PORTABLE_INNER_H
#define MC_PORTABLE_INNER_H
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#define BR_LE_UNALIGNED 0
#define BR_BE_UNALIGNED 0
'''
header += ''.join(f'#define br_aes_ct_{s} mc_bear_aes_ct_{s}\n' for s in symbols)
header += '#define br_ghash_ctmul32 mc_bear_ghash_ctmul32\n'
header += inner[start:end]
header += '''
void br_aes_ct_bitslice_Sbox(uint32_t *q);
void br_aes_ct_bitslice_invSbox(uint32_t *q);
void br_aes_ct_ortho(uint32_t *q);
unsigned br_aes_ct_keysched(uint32_t *comp_skey, const void *key, size_t key_len);
void br_aes_ct_skey_expand(uint32_t *skey, unsigned rounds, const uint32_t *comp);
void br_aes_ct_bitslice_encrypt(unsigned rounds, const uint32_t *skey, uint32_t *q);
void br_aes_ct_bitslice_decrypt(unsigned rounds, const uint32_t *skey, uint32_t *q);
void br_ghash_ctmul32(void *y, const void *h, const void *data, size_t len);
#endif
'''
target = root / 'inner.h'
if args.check:
    if not target.exists() or target.read_text() != header:
        raise SystemExit('stale portable/inner.h; run tools/select-portable-crypto.py')
else:
    target.write_text(header)
print(f"BearSSL: {manifest['commit']}; imports and selected header verified")
