#!/usr/bin/env python3
"""Select verbatim upstream API functions; no arithmetic is rewritten.

The original translation units also export RNG/OS APIs that this package must
not link. Run with --check to verify the checked-in selection and namespace.
This script is an import/review tool, never a build or runtime dependency.
"""
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent / "sr25519"
vendor = root / "vendor/src/libsodium"
selection = {
    "sodium/utils.c": ["sodium_memzero", "sodium_memcmp", "sodium_is_zero", "sodium_add"],
    "crypto_core/ed25519/core_ed25519.c": [
        "crypto_core_ed25519_scalar_reduce", "crypto_core_ed25519_scalar_add"],
    "crypto_core/ed25519/core_ristretto255.c": [
        "crypto_core_ristretto255_is_valid_point", "crypto_core_ristretto255_add",
        "crypto_core_ristretto255_sub", "crypto_core_ristretto255_from_hash",
        "crypto_core_ristretto255_scalar_reduce", "crypto_core_ristretto255_scalar_add",
        "crypto_core_ristretto255_scalar_mul"],
}


def function(source, name):
    start = re.search(r"(?m)^(?:void|int)\n" + re.escape(name) + r"\(", source)
    if start is None:
        raise ValueError(f"missing upstream definition: {name}")
    # Keep offsets while masking comments and string/character literals.
    masked = re.sub(r'/\*.*?\*/|//[^\n]*|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'',
                    lambda m: " " * len(m.group()), source, flags=re.S)
    begin = masked.index("{", start.start())
    depth = 1
    end = begin + 1
    while depth:
        depth += (masked[end] == "{") - (masked[end] == "}")
        end += 1
    return source[start.start():end] + "\n"


generated = "/* Generated by tools/select-sr25519-sodium.py. Verbatim upstream functions. */\n"
for file, functions in selection.items():
    source = (vendor / file).read_text()
    for name in functions:
        generated += f"\n/* {file}: {name} */\n" + function(source, name)

# Namespace every upstream identifier with one of these implementation/API
# prefixes, including static helpers and types, so it can coexist with sodium.
symbols = {"crypto_scalarmult_ristretto255", "crypto_scalarmult_ed25519"}
macros = set()
for file in (root / "vendor").rglob("*"):
    if file.suffix in (".c", ".h"):
        macros.update(re.findall(r"(?m)^\s*#\s*define\s+(\w+)", file.read_text()))
        symbols.update(re.findall(
            r"\b(?:fe25519|ge25519|sc25519|ristretto255|crypto_core_ed25519|"
            r"crypto_core_ristretto255|crypto_scalarmult_ed25519|"
            r"crypto_scalarmult_ristretto255|crypto_verify|sodium)_\w+\b", file.read_text()))
symbols.difference_update(macros)
namespace = "/* Generated namespace; upstream files remain unchanged. */\n"
namespace += "\n".join(f"#define {s} mc_sr_{s}" for s in sorted(symbols)) + "\n"
for name, contents in [("sodium_api.inc", generated), ("sodium_namespace.h", namespace)]:
    path = root / name
    if "--check" in sys.argv:
        if path.read_text() != contents:
            raise SystemExit(f"stale sodium selection: {path}")
    else:
        path.write_text(contents)
print("sr25519 sodium selection and namespace verified" if "--check" in sys.argv else "Generated sr25519 sodium selection and namespace")
